name: ribo_genome
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - python=3.7.12
    - nextflow=19.04.1
    - openjdk=8.0.412
    - samtools=1.18
    - sra-tools=3.2.1
    - fastqc=0.11.8
    - setuptools
    - pip
    - numpy=1.19.5
    - pandas=1.1.5
    - matplotlib=3.3.4
    - bowtie2=2.3.4.3
    - hisat2=2.2.0
    - pysam=0.16.0.1
    - bedtools=2.27.1
    - cutadapt=1.18
    - ucsc-bedgraphtobigwig=472
    - pyyaml=6.0.1
    - click=8.1.8
    - regex=2024.4.16
    - h5py=3.8.0
    - future=1.0.0
    - dill=0.3.7
    - multiprocess=0.70.15
    - pybktree=1.1
    - xopen=1.6.0
    - tornado=6.2
    - typing_extensions=4.7.1
    - zipp=3.15.0
    - toml=0.10.2
    - ply=3.11
    - packaging=23.2
    - pbzip2=1.1.13
    - pigz=2.8
    - coreutils=9.5
    pip:
      - scipy==1.5.4
      - umi_tools==1.1.1
      - git+https://github.com/ribosomeprofiling/ribopy.git
      - -e ./modified_rfcommands 
