# N E X T F L O W
##########################################################################
#####   SAMPLE RIBOFLOW ARGUMENTS FILE WITH RNASEQ AND METADATA   ########
##########################################################################

# Tested on  version 19.04.1

# Perform fastqc at several stages of the pipeline
do_fastqc: true

# Check existnece of fastq.gz files and bowtie2 reference files
do_check_file_existence : true

# Deduplication method: "umi_tools", "position", or "none"
# - "umi_tools": UMI-based deduplication (requires UMI extraction)
# - "position": Position-based deduplication (removes duplicate coordinates)
# - "none": No deduplication performed
dedup_method: "position"

# Enable RNA-seq processing (set to true if you have RNA-seq data)
do_rnaseq: true

# Set to false for genome alignment mode
do_ribo_creation: false

do_metadata: true

clip_arguments: '-u 1 -a CTGTAGGCACCATCAAT --overlap=4 --trimmed-only --maximum-length=40 --minimum-length=15 --quality-cutoff=28'

mapping_quality_cutoff: 2

###############################################################################

alignment_arguments:
   filter:        '-L 15 --no-unal --norc'
   genome: '--no-unal -k 1 --no-softclip --no-spliced-alignment'

###############################################################################

ribo:
    ref_name:        "appris-v1"
    metagene_radius: 50
    left_span:       35
    right_span:      10
    read_length:
       min: 24
       max: 30
    coverage: true

###############################################################################
# Output folder settings
output:
   individual_lane_directory: 'individual'
   merged_lane_directory: 'merged'
   intermediates:
      base: 'intermediates_nodedup'
      clip: 'clip'
      log: 'log'
      transcriptome_alignment: 'transcriptome_alignment'
      filter: 'filter'
      genome_alignment: 'genome_alignment'
      bam_to_bed: 'bam_to_bed_genome'
      quality_filter: 'quality_filter_genome'
      alignment_ribo: 'alignment_ribo_genome' # bigwigs are stored in here.
      bigwigs: 'bigwigs'
   output_genome:
      base: 'output_nodedup'
      log: 'log_genome'
      fastqc: 'fastqc_genome'
      ribo: 'ribo_genome'

###############################################################################

input:
   reference:
      filter: ./rf_sample_data/filter/human_rtRNA*
      regions: ./rf_sample_data/annotation/appris_human_24_01_2019_actual_regions.bed
      transcript_lengths: ./rf_sample_data/annotation/appris_human_24_01_2019_selected.lengths.tsv
      genome: ./rf_sample_data/genome/hisat2_spliced_index*

   fastq_base: ""
   fastq:
       GSM1606107:
         - ./rf_sample_data/fastq/ribosome_profiling/GSM1606107/SRR1795425.fastq.gz
         - ./rf_sample_data/fastq/ribosome_profiling/GSM1606107/SRR1795426.fastq.gz

       GSM1606108:
         - ./rf_sample_data/fastq/ribosome_profiling/GSM1606108/SRR1795427.fastq.gz
         - ./rf_sample_data/fastq/ribosome_profiling/GSM1606108/SRR1795428.fastq.gz

   root_meta: "./project.yaml"

###############################################################################
# P-site Offset Correction (Optional)
# Uncomment and configure if you want P-site correction for ribo-seq data
# P-site correction converts reads to 1bp at the ribosome P-site position
# 
# Requirements:
# - CSV file with experiment-specific P-site offsets per read length
# - Map each sample and lane to an experiment ID from the offset file
# 
# Note: BigWig generation does not require p-site correction

# psite_offset:
#   offset_file: "./outputHuman_OFFSETS.csv"
#   sample_matching:
#     experiment_1:  # must match to input fastq sample name.
#       lanes:
#         1: "GSM2817683"  # Experiment ID from offset CSV
#         2: "GSM2817686"
###############################################################################

###############################################################################
# RNA-seq Configuration

# Key settings:
# - dedup_method: "position" (recommended) or "none"
# - library_strandedness: "reverse" (default, most common) or "forward"
#
# - genome_read_trim: Optional read trimming before genome alignment
#   Set enabled: true and specify length to trim reads after rRNA filtering
#
# Note: RNA-seq bigWigs are automatically generated in:
#       intermediates_*/rnaseq/alignment_ribo/bigwigs/merged/

rnaseq:
  clip_arguments: '-u 1 --quality-cutoff=28'
  fastq_base: ""
  dedup_method: "none"
  library_strandedness: "reverse"  # "forward" or "reverse"
  filter_arguments: '-L 20 --no-unal'
  hisat2_arguments: "--no-unal -k 1 --no-softclip"
  genome_read_trim:  # Optional: trim reads after filtering
    enabled: false
    length: 35
  fastq:
    GSM1606107:
      - ./rf_sample_data/fastq/rnaseq/GSM1606099/SRR1795409.fastq.gz
      - ./rf_sample_data/fastq/rnaseq/GSM1606099/SRR1795410.fastq.gz
    GSM1606108:
      - ./rf_sample_data/fastq/rnaseq/GSM1606100/SRR1795411.fastq.gz
      - ./rf_sample_data/fastq/rnaseq/GSM1606100/SRR1795412.fastq.gz
